apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f network-gateway-latest.yml
    kompose.version: 1.11.0 ()
  creationTimestamp: null
  labels:
    io.kompose.service: admin
  name: admin
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: admin
    spec:
      hostAliases:
      - ip: "127.0.0.1"
        hostnames:
        - "admin"
      containers:
      - image: duosecurity/network-gateway@sha256:d5f142bad8f19d34c31b6ebf877cd217881c62a9dec493d45fc4f8de933741be
        name: network-gateway-admin
        ports:
        - name: https
          containerPort: 443
        - name: admin
          containerPort: 8444
        resources: {}
      restartPolicy: Always
status: {}
